---
- name: Configure Cisco C3750-CX Switch
  hosts: cisco_switch
  gather_facts: no
  tasks:
    - name: Configure trunk on port 9
      ios_config:
        lines:
          - switchport mode trunk
        parents: interface gi0/9
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          authorize: yes
          auth_pass: "{{ ansible_enable_password }}"

    - name: Configure access ports on VLAN 25
      ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 25
          - spanning-tree portfast
        with_items:
          - gi0/1
          - gi0/2
          - gi0/3
          - gi0/4
          - gi0/5
          - gi0/6
          - gi0/7
          - gi0/8
        parents: "interface {{ item }}"
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          authorize: yes
          auth_pass: "{{ ansible_enable_password }}"

    - name: Save configuration
      ios_config:
        lines:
          - do write memory
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          authorize: yes
          auth_pass: "{{ ansible_enable_password }}"
