---
- name: Configure Cisco C3750-CX Switch
  hosts: cisco_switch
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Configure trunk on port 9
      ios_config:
        lines:
          - switchport mode trunk
        parents: interface gi0/9
      register: trunk_result

    - name: Configure access ports on VLAN 25
      ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 25
          - spanning-tree portfast
        loop:
          - gi0/1
          - gi0/2
          - gi0/3
          - gi0/4
          - gi0/5
          - gi0/6
          - gi0/7
          - gi0/8
        parents: "interface {{ item }}"
      register: access_ports_result

    - name: Save playbook results to file
      copy:
        dest: /tmp/playbook_results.json
        content: |
          {
            "trunk_result": {{ trunk_result }},
            "access_ports_result": {{ access_ports_result }}
          }
