- hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run show version on ios device
      cisco.ios.ios_command:
        commands:
          - show version
        host: "{{ inventory_hostname }}"
        username: cisco
        password: cisco
