- hosts: switches
  gather_facts: false
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Check ansible_network_os
      debug:
        msg: "Network OS: {{ ansible_network_os }}"

    - name: Run show version on IOS device
      ios_command:
        commands:
          - show version
